### PR TITLE
consistent errors when using client#action

### PR DESCRIPTION
**Pull request by heavyk**
as suggested in #632

perhaps you may want to do it the other way around, and for xhr, instead `callback({error: err})`

your call.. cheers
[EDIT: fixed the commit msg]

### CODE REVIEW

**Comment by evantahler** [comment]
The problem in your fiddle (mentioned in https://github.com/evantahler/actionhero/pull/632) is that you aren't waiting for the `client.connect()` callback (http://www.actionherojs.com/docs/servers/websocket.html). If wait for the callback properly, then you won't need to handle return values separately depending on if you are connected or not.

You only changed the return value style of action, but if you want to make this change, you should also update all the other commands, like `say`, `roomView`, etc.  Then, we can discuss the change.

**Comment by evantahler** [comment]
Also, this breaks all the tests :(

**Comment by heavyk** [comment]
Jaja... Actually I was thinking about it and I'd rater it all be on one
object and check the error property. I'll change it when I get home and
resend the request... Still haven't tried the middkeware thing. Today was a
long day at work

Cheers!

**Comment by evantahler** [comment]
Closing due to lack of response.   Feel free to open again!

**Pull request closed without merging**
