### PR TITLE
support if-modified-since specifications

### PR DESCRIPTION
**Pull request by lorenzofox3**
This pull request aims to improve the cache capabilities of the web server using "if-modified-since" specification.

### CODE REVIEW

**Comment by lorenzofox3** [comment]
I think it should be fine now, sorry for the mess 
screen shot 2015-10-21 at 09 22 00

**Comment by evantahler** [comment]
nice!  I'll update the other servers for you

**Comment by evantahler** [comment]
Here's the update for websockets: https://github.com/evantahler/actionhero/commit/f9ac949e1b0d8e51c0e3b2c048aeeb96005f3c14

There isn't anything to modify for the socket server

**Comment by lorenzofox3** [comment]
thanks a lot

**Pull request merged**
