### PR TITLE
Fixes resque verbose output

### PR DESCRIPTION
**Pull request by kytwb**
See issue #587.

### CODE REVIEW

**Comment by evantahler** [comment]
Thanks for doing this! There's probably a few other things that should be this new `trace` level:
- Loading files: https://github.com/evantahler/actionhero/blob/master/actionhero.js#L105
- Logging about the Logger: https://github.com/evantahler/actionhero/blob/master/initializers/logger.js#L48
- Route Info: https://github.com/evantahler/actionhero/blob/master/initializers/routes.js#L105 and https://github.com/evantahler/actionhero/blob/master/initializers/routes.js#L117

**Comment by kytwb** [comment]
Done. Let me know if you see more or feel free to merge.

**Comment by evantahler** [comment]
Looks like you haven't actually tried to log something at the `trace` level, it blows us: We need to tell winston the CLI color for our new level, so the logger config block becomes: 

```js
api.logger = new (winston.Logger)({
      levels: {
        emerg: 8,
        alert: 7,
        crit: 6,
        error: 5,
        warning: 4,
        notice: 3,
        info: 2,
        debug: 1,
        trace: 0
      },

      colors: {
        trace: 'magenta',
        input: 'grey',
        verbose: 'cyan',
        prompt: 'grey',
        debug: 'blue',
        info: 'green',
        data: 'grey',
        help: 'cyan',
        warn: 'yellow',
        error: 'red'
      },

      transports: transports
    });
```

we had been previously lucking out because the names of levels were ones Winston had preset as defaults, but `trace` is new.

**Comment by evantahler** [comment]
This is going to be reverted via https://github.com/evantahler/actionhero/pull/712

**Pull request merged**
