### PR TITLE
Fix "connected" event on websocket fired too early

### PR DESCRIPTION
**Pull request by S3bb1**
When you listen on the "connected" event on the websocket connect and you fire immediately a action over the client lib the "actionWeb" function is used instead of the "actionWebSocket" function because ` self.state = 'connected';` is set after the "connected" event is emitted.

This fix solves the problem

### CODE REVIEW

**Comment by l0oky** [comment]
Wait, does It matter If you place that line above or below `If statement` when nodejs runs this non-blocking?

**Comment by S3bb1** [comment]
Try it:

change your index.html (at the bottom) to:

``` javascript
    var client = new ActionheroClient();
    client.connect();
    client.on('connected', function(){
      client.action('showDocumentation', function(data){
        if(data.error){ window.alert(data.error); }
        populateDocumentation(data)
      });

      client.action('status', function(data){
        if(data.error){ window.alert(data.error); }
        populateStatus(data)
      });
    });
```

this **should** wait for the connected event from the websocket. And see the response : 

image


As you can see, the actions are called via actionWeb (REST) instead of websockets.

When you change the line to my pull request the network tab looks like:
image

**Comment by evantahler** [comment]
great catch and explanation! 

I think writing a test for this behavior is a bitt *to* tricky, so we can merge this as-is.

Thanks!

**Comment by l0oky** [comment]
Pardon me, I didn't notice this is from `public/javascript/actionheroClient.js`. Good catch!

**Pull request merged**
