### PR TITLE
Futher Stylistic Changes

### PR DESCRIPTION
**Pull request by krishnaglick**
Based on my last PR, cascading the changes elsewhere.

### CODE REVIEW

**Comment by evantahler** [comment]
Be sure those spaces pass the ESLINT checks.  @synthmeat is the expert here

**Comment by l0oky** [comment]
Are those spaces a ESLINT standard? Cause I am pretty used to the one without the spaces hehe :)

**Comment by krishnaglick** [comment]
Honestly, I don't know. I tend to replicate coding styles I commonly see.
FWIW, here's Ember doing the same thing: https://github.com/emberjs/ember.js/blob/master/tests/node/component-rendering-test.js

**Comment by synthmeat** [comment]
@krishnaglick No, the existing codebase before adding ESLint didn't have space. It's pretty dense style all in all.

@l0oky One of the reasons for the move to ESLint was that it has no rules by default.

@evantahler I'll make a grunt task to check as well as autofix the code according to the style this weekend.

**Comment by synthmeat** [comment]
@evantahler Well, not grunt task. npm script. Didn't even notice grunt's gone! :)

**Comment by krishnaglick** [comment]
Do we wanna merge this (since the other PR was), or drop it and let the task do its thing?

**Comment by evantahler** [comment]
rebase master onto your branch, and try the new `npm run lint` @synthmeat just made!

**Comment by krishnaglick** [comment]
I got 11,906 of...
"Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style"
Windows lol....

**Pull request closed without merging**
