### PR TITLE
This actually needs to be `undefined`

### PR DESCRIPTION
**Pull request by submitteddenied**
Just a simple correction of documentation here.

It would also be totally reasonable to change this back to `null` and correct where the config is used in `servers/websocket.js:166`.

### CODE REVIEW

**Comment by submitteddenied** [comment]
Ah, I see my editor has taken liberties with your whitespace too. Sorry about the messy diff :\

**Comment by evantahler** [comment]
I think that the right thing to do is in `servers/websocket.js:166` allow both `null` and `undefined`.

**Comment by evantahler** [comment]
Bump.  Need any help here?

**Comment by submitteddenied** [comment]
I have updated it so that falsey values will prevent client side JS from being generated

**Comment by evantahler** [comment]
Great! Thanks!

**Pull request merged**
