### PR TITLE
Fix ETAG issue for files

### PR DESCRIPTION
**Pull request by S3bb1**
We've found a issue with the etags, every file had the same etag. This was because fileStream.toString() is [object Object] and not the content istself. So every ETAG was generated for [object Object]

I've added a test to check if the ETAG is NOT the same for different files.

### CODE REVIEW

**Comment by evantahler** [comment]
great find!

However, don't use a `sync` fall to the filesystem, as this will block all other operations.

**Comment by S3bb1** [comment]
yeah, good point. I will adjust this to be async

**Comment by evantahler** [comment]
bump?

**Comment by S3bb1** [comment]
Sorry for the delay, was a little busy the last days. I will push the changes today.

**Comment by evantahler** [comment]
Yay!

**Pull request merged**
