### PR TITLE
NODE_ENV fix for Windows

### PR DESCRIPTION
**Pull request by krishnaglick**
This gets tests running on Windows but I don't know if it breaks Unix systems.

### CODE REVIEW

**Comment by krishnaglick** [comment]
Well, it looks like it does. :/

**Comment by evantahler** [comment]
It looks like folks have gone through a ton of hackery to get stuff like this working, as evidenced by packages like https://www.npmjs.com/package/cross-env and this conversation about NPM itself https://github.com/npm/npm/issues/10575

I guess the right thing to do here is to make a single node script in the `/test/run-test.js` directory.  It would be a little JS file which will detect the OS (check `process.platform`), and then uses the a child process to actually call out to mocha.   This is vaguely what NPM recommends in this note https://github.com/npm/npm/issues/2800

**Comment by evantahler** [comment]
This is also why the fancy packages use makefiles for this too https://github.com/mochajs/mocha/blob/master/Makefile

I was going to suggest a bash script to wrap this all... but then again... windows :(

**Comment by krishnaglick** [comment]
I'm gonna say this isn't worth the work unless some adventurous young dev wants to go through the trouble.
Maybe mark it as a low priority error?

**Comment by evantahler** [comment]
Marked!

**Comment by evantahler** [comment]
closing in favor of https://github.com/evantahler/actionhero/pull/790

**Pull request closed without merging**
