### PR TITLE
Symlink Plugins

### PR DESCRIPTION
**Pull request by evantahler**
- create the binary command `actionhero link --name=name_of_plugin`
- remove the plugin-specific code from the config initializer 
- remove the old plugin tests

## Plugin Registration

When running `actionhero link --name=name_of_plugin`, we look though your `api.config.general.paths.plugin` (which contains `./node_modules` by default) for the named plugin.  If we find it, we symlink in the actions, initializers, tasks, and servers found there.  These files will then be "present" in your project via that linkfile.  A linkfile is a simple file with the name of `{pluginName}.link` in the top level folder of that type of thing (like actions or tasks)

For example, if you install `myPlugin` via `npm install --save myPlugin` into your project's `./node_modules` folder, and then `npm run actionhero link --name myPlugin`, this will work perfectly.  

Files found in the `/config` directory of the plugin will be copied into your project's top level `config` directory.  This is under the assumption that you will want to modify these settings.  Config files within a plugin itself will not get sourced.

A previous version of this tool used OS symlinks, but that was removed to enable cross-platform compatibility. 

## Nested Plugins (TODO)

The good news is that we can count on NPM to properly (relatively) install any dependent plugins as a child in their local `node_modules`, so it shouldn't be too hard. 

## Notes for Plugin Authors
- There should be no more postinstall scripts needed
- Remember that any files in `/config` will get automatically copied into the user's project when they run `actionhero link`.  Make sure that you have some good comments!
- Be sure that your plugin is OS-independant.  Use `path.sep` for file path separators and things like that.  Use relative paths for everything in your plugin.

### CODE REVIEW

**Comment by evantahler** [comment]
@neilstuartcraig, @l0oky, @hutchike, @slattery @AngeloR what are your thoughts?
Does anyone have a windows computer they can try this out on?

**Comment by neilstuartcraig** [comment]
@evantahler - i'll try to take a look today/tomorrow - got some nginx/openssl builds to fix up first.

Which windows versions do you want to target? I might be able to persuade a colleague or maybe use the [MSFT VMs](https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/) to test - assuming i can remember how to do anything on windows these days :-)

**Comment by AngeloR** [comment]
I will only have access to a windows machine this evening (EST) around 7pm. Will test there. Are there any particular edge cases you require tested? or just running the built in tests is enough?

**Comment by evantahler** [comment]
The main thing to test on windows right now is if it works at all :D 
So to test this, you'll need to 'make' a plugin:

- check out this project and `npm install`
- make a new `plugins` directory and add it to `api.config.general.paths.plugin` array
- make a new plugin, `myPlugin` and add some actions and tasks to it.
- try to link the new plugin via `actionhero link myPlugin`
- report back on how it went.

node *says* that [symlink commands](https://github.com/evantahler/actionhero/pull/758/files#diff-58d3143ac051465eb40f4c54282b63ccR97) should be cross platform... so lets find out! 

Thanks!

**Comment by evantahler** [comment]
was anyone able to test on windows?

**Comment by hutchike** [comment]
Sorry I'm Mac-only, with Ubuntu servers, so no opportunity to test
sym-links on MS Win.

**Comment by S3bb1** [comment]
I tried it on Win10 and the "link" command works, but then the start fails.

C:\Temp\ah\actionhero-plugins\actionhero-plugins>node bin\actionhero link --name
 myPlugin
2016-01-21T20:12:14.828Z - info: actionhero >> link
2016-01-21T20:12:14.831Z - info: linking the plugin found at plugins\myPlugin
2016-01-21T20:12:14.831Z - info:  - creating symbolic link 'C:\Temp\ah\actionher
o-plugins\actionhero-plugins\actions\myPlugin' => '..\plugins\myPlugin\actions'

C:\Temp\ah\actionhero-plugins\actionhero-plugins>npm start



> actionhero@13.0.0 start C:\Temp\ah\actionhero-plugins\actionhero-plugins
> node ./bin/actionhero

2016-01-21T20:12:20.537Z - info: actionhero >> start
2016-01-21T20:12:20.709Z - notice: *** starting actionhero ***
2016-01-21T20:12:20.756Z - warning: running with fakeredis

fs.js:659
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOTDIR, not a directory 'C:\Temp\ah\actionhero-plugins\actionhero-plugin
s\actions\myPlugin'
    at Object.fs.readdirSync (fs.js:659:18)
    at Object.api.utils.recursiveDirectoryGlob (C:\Temp\ah\actionhero-plugins\ac
tionhero-plugins\initializers\utils.js:111:12)
    at C:\Temp\ah\actionhero-plugins\actionhero-plugins\initializers\utils.js:11
7:33
    at Array.forEach (native)
    at Object.api.utils.recursiveDirectoryGlob (C:\Temp\ah\actionhero-plugins\ac
tionhero-plugins\initializers\utils.js:111:29)
    at C:\Temp\ah\actionhero-plugins\actionhero-plugins\initializers\actions.js:
102:17
    at Array.forEach (native)
    at Object.module.exports.initialize (C:\Temp\ah\actionhero-plugins\actionher
o-plugins\initializers\actions.js:101:37)
    at loadFunction (C:\Temp\ah\actionhero-plugins\actionhero-plugins\actionhero
.js:142:44)
    at C:\Temp\ah\actionhero-plugins\actionhero-plugins\node_modules\async\lib\a
sync.js:718:13

in the actions folder now there is a .symlink file 

image

i try to check this why this error is thrown

**Comment by S3bb1** [comment]
See #761 this additional Parameter fixes the issue. Action is now available

image

**Comment by evantahler** [comment]
As much as I love the simplicity of the symlink approach, there are too many problems:
- Cross-OS issues when developing on windows and deploying to *nix
- Accidental check in of symlink'd files
- The need to run `actionhero link` on production servers as part of deployment.

I'm going to steal the philosophy of this approach and do what a symlink does at the OS level inside actionhero: use `plugin.link` files, when present in the proper directory, to signal a scan of the plugins paths.

**Pull request merged**
