### PR TITLE
add support for removing stuck old workers (resque v0.13)

### PR DESCRIPTION
**Pull request by S3bb1**
- added config for disabling/enabling the removeStuckWorkers function
- added logmessages when stuck workers are removed
- increased package.json for node-resque

### CODE REVIEW

**Comment by S3bb1** [comment]
hm travis don't loves me ... but i think my changes does not affect the failed test

**Comment by evantahler** [comment]
It's fine to bump the `node-resque` version, but I don't even want to allow this as a boot option (It is way to dangerous).    I think that we should note in the docs that this is a thing you can do, but it's up to the user to implement this in their own project.

**Comment by evantahler** [comment]
This issue will be solved by this PR https://github.com/evantahler/actionhero/issues/654#issuecomment-101665471

**Comment by evantahler** [comment]
Let me know when you make those changes!

**Comment by S3bb1** [comment]
I've moved the logic to the docs and reused the text from node-resque, Hope this is okay for you @evantahler

**Comment by evantahler** [comment]
Merged!

**Pull request merged**
