### PR TITLE
Added watchFolderAndAct()

### PR DESCRIPTION
**Pull request by paulxtiseo**
Added watchFolderAndAct() + docs. Not sure if I should have added tests, but could not find tests for the existing watchFileAndAct() anyways.

### CODE REVIEW

**Comment by l0oky** [comment]
Your pull request seems to fail tests

**Comment by evantahler** [comment]
Yup, looks like tests fail here.  Also:
- Please add a test which demonstrates and "locks in" your new functionality
- This new feature seems to replace some of the code that exists (in action, init, and task loaders).  Please refactor the code to use this new method!

**Comment by paulxtiseo** [comment]
- Where do I put a test for a new API function.
- I believe on the second point I added a second test to an if statement (line 122) to `initializers/utils.js` that may be a problem? If so, I'm not sure how to "refactor the code to use this new method"?

**Comment by evantahler** [comment]
@paulxtiseo Bump?

**Comment by evantahler** [comment]
you can put the test here perhaps https://github.com/evantahler/actionhero/blob/master/test/core/api.js, or just make a new file, that's OK too. 

As far as refactoring, looking though the code again, it's rare that we are watching whole folders (and events happen on the file more than the folder), so maybe there's no refactoring needed.

**Comment by evantahler** [comment]
Closing this due to lack of updates

**Pull request closed without merging**
