### PR TITLE
input methods have `api` set as `this`

### PR DESCRIPTION
**Pull request by evantahler**
Since `formatter`, `validator`, and `default` are sync methods, we can change their `this` to be API.  That will be handy.

### CODE REVIEW

**Comment by paulxtiseo** [comment]
When I use a `console.log(this)` in the input validator, I get the action, not the api, object. Is this what was intended? I have AH v13.3.1.

**Comment by evantahler** [comment]
@paulxtiseo are you certain?  It's pretty clearly calling `call` with `api` as the scope https://github.com/evantahler/actionhero/blob/master/initializers/actionProcessor.js#L196-L215

**Comment by paulxtiseo** [comment]
My apologies. I was using a fat arrow for the validator function.

**Comment by evantahler** [comment]
... adding new meaning to `keep it lean`

**Pull request merged**
