### PR TITLE
resolve issue with additional "." in initalizer path

### PR DESCRIPTION
**Pull request by S3bb1**
if your current folder contains any "." in it ... all initalizers will break. this PR uses a nodejs path function to solve this.

### CODE REVIEW

**Comment by evantahler** [comment]
nice.

**Comment by jacobbubu** [comment]
Could make it more consistent via `path.extname`:

```js
var initializer = path.basename(f).split('.')[0];
if (path.extname(file) === '.js') {
     ...
}
```

**Comment by S3bb1** [comment]
yeah, looks good maybe we could replace the "f" variable with the "file" variable in the basename parameter too.

``` javascript
var initializer = path.basename(file).split('.')[0];
if (path.extname(file) === '.js') {
     ...
}
```

**Comment by evantahler** [comment]
You can update this branch and send a new PR from it!

**Pull request merged**
