### PR TITLE
Adds hooks for before_enqueue and after_enqueue to task middleware.

### PR DESCRIPTION
**Pull request by gcoonrod**
Addresses https://github.com/evantahler/actionhero/issues/899

@evantahler: I think it really is this easy.

### CODE REVIEW

**Comment by evantahler** [comment]
Could be! 
Can you please add some tests to lock in the functionality?

**Comment by gcoonrod** [comment]
Slight gotcha on the enqueue hooks. Sending an error in the before_enqueue `next` isn't enough to prevent the task from being enqueued. You must explicitly pass `false` for `toRun`.

**Comment by evantahler** [comment]
@gcoonrod ready to merge?  LGTM!

**Comment by gcoonrod** [comment]
I'm ready to merge.

**Comment by evantahler** [comment]
Oh! @gcoonrod We need Documentation!

**Comment by gcoonrod** [comment]
Docs added!

**Comment by evantahler** [comment]
YAY!

**Pull request merged**
